class ProfanityFilter
    def initialize
        #upon instantiation, the profanity words array is used as a filter to remove all the innappropriate words from a string before a message is saved to the db
        @profanity_words_array = [
            '2g1c',
            '2 girls 1 cup',
            'acrotomophilia',
            'Alexis Texas',
            'alexis texas',
            'anal',
            'Anal',
            'anilingus',
            'Anilingus',
            'anus',
            'Anus',
            'arse',
            'Arse',
            'Arsehole',
            'arsehole',
            'ass',
            'assnigga',
            'Ass nigga',
            'Ass',
            'asshole',
            'Asshole',
            'Assmunch',
            'assmunch',
            'Auto erotic',
            'auto erotic',
            'autoerotic',
            'babeland',
            'baby batter',
            'ball gag',
            'ball gravy',
            'ball kicking',
            'ball licking',
            'ball sack',
            'Ball sack',
            'ball sucking',
            'Ball sucking',
            'bangbros',
            'Bang bros',
            'bareback',
            'barely legal',
            'Barely legal',
            'barenaked',
            'Bare naked',
            'bastardo',
            'bastinado',
            'bbw',
            'Bbw',
            'BBC',
            'bbc',
            'Bbc',
            'BBW',
            'bdsm',
            'Bdsm',
            'BDSM',
            'beaver cleaver',
            'beaver lips',
            'bestiality',
            'Beastiality',
            'beastiality',
            'bi curious',
            'big black',
            'Big black',
            'big breasts',
            'Big Breasts',
            'Big breasts',
            'big knockers',
            'Big Knockers',
            'Big Tits',
            'big tits',
            'Bimbo',
            'bimbo',
            'bimbos',
            'birdlock',
            'bitch',
            'bitchassnigga',
            'bitchass',
            'Bitch',
            'black cock',
            'Black cock',
            'Black Cock',
            'blonde action',
            'blonde on blonde action',
            'blow j',
            'Blow Job',
            'Blow job',
            'blow your l',
            'blowy',
            'Blowy',
            'blue waffle',
            'blumpkin',
            'bollocks',
            'bondage',
            'boner',
            'boob',
            'boobs',
            'boobies',
            'boobie',
            'Boob',
            'Boobies',
            'booty call',
            'brown showers',
            'brunette action',
            'bukkake',
            'bulldyke',
            'bullet vibe',
            'bung hole',
            'bunghole',
            'busty',
            'bust a nut',
            'Bust a nut',
            'buttcheeks',
            'butthole',
            'camel toe',
            'camgirl',
            'cam girl',
            'Cam girl',
            'Cam slut',
            'camslut',
            'camwhore',
            'carpet muncher',
            'carpetmuncher',
            'chocolate rosebuds',
            'circlejerk',
            'cleveland steamer',
            'Clit',
            'clit',
            'clitoris',
            'Clitoris',
            'clover clamps',
            'clusterfuck',
            'cock',
            'Cock',
            'cocks',
            'coochie',
            'Coochie',
            'coochie mama',
            'Coochie Mama',
            'coprolagnia',
            'coprophilia',
            'cornhole',
            'cum',
            'Cum',
            'I cum',
            'cumming',
            'cunnilingus',
            'cunt',
            'Cunt',
            'darkie',
            'date rape',
            'daterape',
            'deep throat',
            'deepthroat',
            'dick',
            'dickhead',
            'Dickhead',
            'Dick',
            'Dildo',
            'dildo',
            'dirty sanchez',
            'dog style',
            'Doggie style',
            'doggie style',
            'doggiestyle',
            'doggy style',
            'doggystyle',
            'dolcett',
            'dominatrix',
            'dommes',
            'donkey punch',
            'double dong',
            'double penetration',
            'dp action',
            'eat my ass',
            'Eat my ass',
            'ecchi',
            'ejaculation',
            'Ejaculate',
            'erotic',
            'erotism',
            'escort',
            'Escort',
            'ethical slut',
            'eunuch',
            'faggot',
            'Faggot',
            'fecal',
            'Fecal',
            'felch',
            'fellatio',
            'feltch',
            'female squirting',
            'femdom',
            'figging',
            'fingering',
            'Fingering',
            'fisting',
            'Fisting',
            'foot fetish',
            'Foot Fetish',
            'Foot fetish',
            'footjob',
            'frotting',
            'Fuck',
            'FUCK',
            'fuck',
            'fucking',
            'FUCKING',
            'Fucking',
            'fucker',
            'Fucker',
            'FUCKER',
            'Fucks',
            "FUCKS",
            'fucks',
            'fuck me',
            'FUCKME',
            'fuckme',
            'fuckyou',
            'FUCKYOU',
            'FUCKyou',
            'FuckYou',
            'Fuck me',
            'Fuck Me',
            'fuck buttons',
            'fudge packer',
            'fudgepacker',
            'futanari',
            'g-spot',
            'G-spot',
            'gang bang',
            'gay sex',
            'gay',
            'Gay',
            'GAY',
            'G A Y',
            'g a y',
            'genitals',
            'giant cock',            
            'girls gone wild',
            'goatcx',
            'goatse',
            'gokkun',
            'golden shower',
            'goo girl',
            'goodpoop',
            'goregasm',
            'grope',
            'group sex',
            'Group sex',
            'groupie',
            'guro',
            'hand job',
            'handjob',
            'hentai',
            'homoerotic',
            'honkey',
            'hooker',
            'Hook up',
            'hook up',
            'hoe',
            'ho',
            'heaux',
            'hot chick',
            'how to kill',
            'how to murder',
            'huge fat',
            'humping',
            'dry hump',
            'horny',
            'hit it from the back',
            'incest',
            'intercourse',
            'jack off',
            'Jack off',
            'jail bait',
            'jailbait',
            'jerk off',
            'jigaboo',
            'jiggaboo',
            'jiggerboo',
            'jizz',
            'juggs',
            'kike',
            'kinbaku',
            'kinkster',
            'kinky',
            'knobbing',
            'leather restraint',
            'Lana R',
            'Lana r',
            'lana r',
            'lemon party',
            'lolita',
            'make me come',
            'male squirting',
            'masturbate',
            'menage a trois',
            'milf',
            'MILF',
            'Milf',
            'missionary position',
            'motherfucker',
            'mound of venus',
            'mr hands',
            'muff diver',
            'muffdiving',
            'nambla',
            'nawashi',
            'negro',
            'Negro',
            'neonazi',
            'nig nog',
            'nigga',
            'niggas',
            'Nigga',
            'Niggas',
            'NIGGA',
            'Nigger',
            'Negro',
            'nigger',
            'niggers',
            'NIGGERS',
            'Niggers',
            'NIGGER',
            'nimphomania',
            'nipple',
            'nipples',
            'nsfw images',
            'nude',
            'Nude',
            'NUDE',
            'NUDES',
            'Nudes',
            'nudes',
            'nudity',
            'nympho',
            'nymphomania',
            'octopussy',
            'omorashi',
            'one cup two girls',
            'one guy one jar',
            'orgasm',
            'orgy',
            'pawg',
            'PAWG',
            'Pawg',
            'paedophile',
            'pedo',
            'panties',
            'Panties',
            'Panty',
            'panty',
            'pedobear',
            'pedophile',
            'pegging',
            'penis',
            'Penis',
            'phone sex',
            'piece of shit',
            'piss pig',
            'pissing',
            'pisspig',
            'playboy',
            'pleasure chest',
            'pole smoker',
            'ponyplay',
            'poof',
            'poop chute',
            'poopchute',
            'porn',
            'Porn',
            'PORN',
            'Porn Hub',
            'pornhub',
            'porn hub',
            'PornHub',
            'porno',
            'pornography',
            'prince albert piercing',
            'pthc',
            'pubes',
            'Pubes',
            'pum pum',
            'pussy',
            'pussies',
            'PUSSY',
            'Pussy',
            'Punani',
            'punani',
            'onlyfans',
            'only fans',
            'Only fans',
            'porn star',
            "Porn Star",
            'queaf',
            'raghead',
            'raging boner',
            'rape',
            'Rape',
            'raping',
            'rapist',
            'rectum',
            'reverse cowgirl',
            'rimjob',
            'rimming',
            'rosy palm',
            'rosy palm and her 5 sisters',
            'rusty trombone',
            's&m',
            'sadism',
            'scat',
            'schlong',
            'Shlong',
            'scissoring',
            'semen',
            'Semen',
            'sex',
            'Sex',
            'SEX',
            'sext',
            'Sext',
            'sexting',
            'Sexting',
            'sexo',
            'sexy',
            'Sexy',
            'shaved beaver',
            'shaved pussy',
            'Shaved pussy',
            'Shave pussy',
            'shemale',
            'shibari',
            'SHIT',
            'suck my',
            'Suck my',
            'shit',
            'Shit',
            'shota',
            'shrimping',
            'slanteye',
            'slut',
            'Slut',
            'Treesh',
            'treesh',
            'send nudes',
            'Send Nudes',
            'smut',
            'snatch',
            'snowballing',
            'sodomize',
            'sodomy',
            'spic',
            'spooge',
            'spread legs',
            'strap on',
            'strapon',
            'strappado',
            'stripper',
            'strip club',
            'style doggy',
            'sultry women',
            'swastika',
            'swinger',
            'swingers',
            'Swingers',
            'tainted love',
            'taste my',
            'tea bagging',
            'Threesome',
            'threesome',
            'foursome',
            'Foursome',
            'fivesome',
            'Threesome',
            'Fivesome',
            'throating',
            'Throating',
            'tied up',
            'tight white',
            'tit',
            'Tit',
            'tits',
            'Tit',
            'titties',
            'titty',
            'Titty',
            'Titties',
            'tongue in a',
            'topless',
            'tosser',
            'thot',
            'Thot',
            'THOT',
            'Thottie',
            'thottie',
            'towelhead',
            'tranny',
            'tribadism',
            'tub girl',
            'tubgirl',
            'tushy',
            'thrust',
            'twat',
            'Twat',
            'twink',
            'twerk',
            'two girls one cup',
            'undressing',
            'upskirt',
            'urethra play',
            'urophilia',
            'vagina',
            'vajayjay',
            'Vag',
            'vag',
            'Vagina',
            'vaginal',
            'VAGINA',
            'venus mound',
            'vibrator',
            'violet blue',
            'violet wand',
            'vorarephilia',
            'voyeur',
            'vulva',
            'wank',
            'wanker',
            'wet dream',
            'wetback',
            'white power',
            'women rapping',
            'wrapping men',
            'wrinkled starfish',
            'xx',
            'xxx',
            'yaoi',
            'yellow showers',
            'yiffy',
            'zoophilia']
    end
    # filters a message text body for innappropriate words and phrases. Returns a string representing the filtered body.
    def filter_message(text)
        #for now the words are split by a space. If any word matches with any of the popular english curse words then the word is simply replaced with an empty string
        words = text.split(" ") #words are split by a space
        words.delete_if {|word| @profanity_words_array.include?(word)}
        text = words.join(" ")
    end
    


end