json.id @post.id
json.caption @post.caption
json.created_at @post.created_at
json.updated_at @post.updated_at
json.views @post.view_count
json.comments_count @post.comments_count
json.likes @post.likes_count
json.media_url @post.media_url
json.thumbnail_url @post.thumbnail_url